---
services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    ports:
      - 32400:32400
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - VERSION=docker
      - PLEX_CLAIM=${PLEX_CLAIM}
    volumes:
      - /Users/scottrobinson/Documents/dev-stuff/docker-stuff/plex/library:/config
      - /Users/scottrobinson/Documents/dev-stuff/docker-stuff/plex/tvseries:/tv
      - /Users/scottrobinson/Documents/dev-stuff/docker-stuff/plex/movies:/movies
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - /Users/scottrobinson/Documents/dev-stuff/docker-stuff/plex/qbittorrent:/config
      - /Users/scottrobinson/Documents/dev-stuff/docker-stuff/plex/downloads:/downloads #optional
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /Users/scottrobinson/Documents/dev-stuff/docker-stuff/plex/prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /Users/scottrobinson/Documents/dev-stuff/docker-stuff/plex/sonarr:/config
      - /Users/scottrobinson/Documents/dev-stuff/docker-stuff/plex/tvseries:/tv #optional
      - /Users/scottrobinson/Documents/dev-stuff/docker-stuff/plex/downloads:/downloads #optional
    ports:
      - 8989:8989
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /Users/scottrobinson/Documents/dev-stuff/docker-stuff/plex/radarr:/config
      - /Users/scottrobinson/Documents/dev-stuff/docker-stuff/plex/movies:/movies #optional
      - /Users/scottrobinson/Documents/dev-stuff/docker-stuff/plex/downloads:/downloads #optional
    ports:
      - 7878:7878
    restart: unless-stopped

